export const sampleExpenses = [
  {
    id: 1,
    description: "Grocery Shopping",
    amount: 85.5,
    category: "Food",
    date: "2025-10-01",
  },
  {
    id: 2,
    description: "Uber to Office",
    amount: 12.3,
    category: "Transportation",
    date: "2025-10-02",
  },
  {
    id: 3,
    description: "Netflix Subscription",
    amount: 15.99,
    category: "Entertainment",
    date: "2025-10-03",
  },
  {
    id: 4,
    description: "Electric Bill",
    amount: 120.0,
    category: "Bills",
    date: "2025-10-04",
  },
  {
    id: 5,
    description: "Coffee at Starbucks",
    amount: 6.75,
    category: "Food",
    date: "2025-10-05",
  },
  {
    id: 6,
    description: "New Headphones",
    amount: 79.99,
    category: "Shopping",
    date: "2025-10-05",
  },
  {
    id: 7,
    description: "Gas Station",
    amount: 45.0,
    category: "Transportation",
    date: "2025-10-06",
  },
  {
    id: 8,
    description: "Movie Tickets",
    amount: 28.0,
    category: "Entertainment",
    date: "2025-10-06",
  },
  {
    id: 9,
    description: "Restaurant Dinner",
    amount: 65.4,
    category: "Food",
    date: "2025-10-07",
  },
  {
    id: 10,
    description: "Internet Bill",
    amount: 59.99,
    category: "Bills",
    date: "2025-10-08",
  },
];
